### ISSUE TITLE
High-pitched sound when launching a box 

### ISSUE THREAD

**Issue by pacoarcade** [jotego/jtdd#15]
Since 20210115 I've noticed scratchy sound and a high-pitched note when the enemies launch boxes. I use MiSTer updated yesterday.

Audio:
[jtdd2-20210115.zip](https://github.com/jotego/jtdd/files/5824683/jtdd2-20210115.zip)

**Comment by jotego** [comment]
I think the antialiasing is supposed to be heard. At least the original DD1 did not have an AA filter.

![imagen](https://user-images.githubusercontent.com/1863036/104817347-fb1b4c00-5820-11eb-960e-bf7a70dc02ac.png)

The output amplifier has a 20kHz bandwidth, so it will not cut-off the aliasing.

I do think this is meant to be heard this way at the output of the arcade PCB board. At the speakers, it may sound different depending on other factors.

**Comment by jotego** [comment]
Let me know if this version sounds ok for you
[jtdd2_20210117.rbf.zip](https://github.com/jotego/jtdd/files/5825668/jtdd2_20210117.rbf.zip)

**Comment by pacoarcade** [comment]
This one sounds perfect!

**Comment by jotego** [comment]
Great. I have replaced the one in the server by this.
