### ISSUE TITLE
Issues with two-button moves

### ISSUE THREAD

**Issue by SpiralBrad** [jotego/jtdd#16]
As of the last few versions of this core (2-3? more perhaps, can't remember when it last worked correctly)...

I've noticed issues with the two-button moves - away-from-enemy + jump + attack in both games.

In Double Dragon 1, pressing away+punch will do the elbow move ONCE; you are then UNABLE to attack until you press the jump button twice.  The first press of jump does nothing, the second press will jump, and you are then able to attack again.  Very odd.

In Double Dragon 2, you are only able to do the away + jump + attack moves toward the left (pressing right) - doing them to the right (pressing left) - simply attacks normally, never doing either special move.  Didn't notice being unable to attack or anything though.

I've reset the core settings on both games AND redefined the controls, so it's not some weird issue of mis-defined buttons or old settings.

**Comment by SpiralBrad** [comment]
Apologies; this seems to be a VERY strange issue with an 8bitdo SN30 Pro controller, over bluetooth only (?) - I've noticed no similar issues in other cores, and connecting this same controller with a USB cable shows the problem to not exist.  So it's not (exactly?) the core... either way, closing this for now.

Super weird.

**Comment by jotego** [comment]
I'm glad you found more about it.
