### ISSUE TITLE
non-flipped screen issues

### ISSUE THREAD

**Issue by ItsAtomico** [jotego/jtdd#17]
Probably not worth noting, but game's kinda broken if you don't flip the screen. 

Notice the displaced garage shutter and player sprites in relation to the background:
![20210212_192758-screen](https://user-images.githubusercontent.com/69975383/107829801-40bc2d80-6d69-11eb-887d-9302f72164e6.png)
![20210212_192759-screen](https://user-images.githubusercontent.com/69975383/107829802-4154c400-6d69-11eb-8973-0dae790dc321.png)

Also walking to the right edge of the screen makes it scroll to the left...

Everything is fine when you flip the screen, so it's kind of a non-issue. Just posting it as a curiosity
ddragon 210207, HDMI

**Comment by jotego** [comment]
Thanks. I'm actually aware of it but as the game isn't vertical I don't think anyone is using the flipped mode. There is a use case: cocktail tables. But apparently no one is using them in the MiSTer community. 

I'll leave this open and fix it when I have an hour free for completion.

**Comment by jotego** [comment]
I have added a note in the README file stating that this won't be supported. 
commit 27f33a8
