### ISSUE TITLE
Config dipswitch missing!! 

### ISSUE THREAD

**Issue by Julitium** [jotego/jtdd#18]
Hello.
The dipswitch settings (difficulty, lives, etc.) do not appear in the OSD In the latest versions.
Could you please include this again. Now config is random. 
Thank you very much.

**Comment by jotego** [comment]
Hello, which FPGA system do you use?

**Comment by Julitium** [comment]
Hi.
Its MiST. 
Thank you very much.

**Comment by jotego** [comment]
You have to use the mra tool to generate an ARC file. Then you boot the core using that ARC file, and not the RBF. The ARC includes the DIP switch information for the OSD.
Be sure to use a recent firmware.
Check the MiST forum if you need specific help about using the mra tool or updating the firmware.
