### ISSUE TITLE
En la fase 3 se me ha volteado la pantalla sola

### ISSUE THREAD

**Issue by vastago** [jotego/jtdd#19]
Por otro lado le tengo que dar cuatro veces a la tecla 5 para obtener un crédito, y cuando empieza el juego tengo 9 vidas pero en realidad son vidas infinitas, porque aunque mueras sigue poniendo 9 vidas.  Lo que hago para actualizar es quitar el rbf antiguo y poner el nuevo jtdd_20210213.rbf, lo renombro a jtdd.rbf. 

El firm de la MIST es ATH210130, conectada a la tele por SCART

![dd](https://user-images.githubusercontent.com/47063821/108767636-eedc8a00-7556-11eb-8487-f2ea8ba4893c.jpg)

**Comment by jotego** [comment]
Prueba a borrar el fichero de configuración que graba MiST. Y arranca el juego con el ARC y no con el RBF directamente.

**Comment by vastago** [comment]
¡¡**Gracias**¡!!, ahora parece que funciona mucho mejor. Nunca había usado la herramienta mra y los archivos ARC porque creía que eso era solo para MISTER, pero en MIST también funciona. Me ha costado un poco conseguirlo, en parte porque a veces no he bajado los ficheros correctamente de github (sobre todo los ficheros mra) y me daba error. También al haber dos formas de generar las roms me he liado un poco, porque al principio no le cogia el truco al mra y pensaba que a lo mejor solo era para MISTER y que al tener la MIST tenia que generar la rom como antiguamente con los ficheros batch.
