### ISSUE TITLE
Double Dragon 2 - Crashes during attract mode

### ISSUE THREAD

**Issue by ItsAtomico** [jotego/jtdd#20]
Game crashes/freezes at different points after running the demo loop for a couple of minutes.

Most users got this screen
![20210422_143222](https://user-images.githubusercontent.com/69975383/115761479-c0253900-a378-11eb-95d9-a33a32fc25f5.jpg).

I've also seen it freeze to a blank off-white screen and during these transitions:
![20210422_144414-screen](https://user-images.githubusercontent.com/69975383/115762018-6113f400-a379-11eb-93aa-6761744e08e0.png).
![20210422_145102-screen](https://user-images.githubusercontent.com/69975383/115762938-5b6ade00-a37a-11eb-9dc4-e438c941d1e7.png)

Resetting the game gets it working again, but it freezes again after a while.

**Comment by jotego** [comment]
Can you pass the 48MHz memory test?

**Comment by ItsAtomico** [comment]
Yeah, regular MiSTer version and both tests you posted ages ago were all fine.

No issues with your previous cores, either. 

> Can you pass the 48MHz memory test?

**Comment by jotego** [comment]
This was fixed but I forgot to close the issue, sorry.
