### ISSUE TITLE
Double Dragon 1 & 2 - Incorrect aspect ratio, Upside-down image by default

### ISSUE THREAD

**Issue by M-Walrus** [jotego/jtdd#22]
HDMI and Analog aspect ratios are very different.  Wider on HDMI in both.
I'm not sure which one is correct, but this should be standardized so the image looks equivalent on both.

Dip switch for flipping screen is reversed, resulting in an upside-down image when "off"t, requiring the dip to be flipped to display properly. 

Graphics corruption when in default flipped mode (both games), as reported in https://github.com/jotego/jtdd/issues/17

**Comment by jotego** [comment]
For the aspect ratio, I don't think I can provide a good default value, as discussed in other issues. But users can use their own. One more reason for this is that HDMI screens tend to apply some scaling by their own -at least mine does- so it is even harder to set a good value.

I have modified the DIP setting so it has the right behaviour when set to OFF. Thanks for pointing it out.

commit 27f33a8

**Comment by M-Walrus** [comment]
Thanks for your attention here Jotego.  I think a good way to do cores like this that have a very large difference in default/4:3 aspect ratios, would be to bake in a selection for this by default.  If you check out the Konami arcade cores by Ace he does the original scaling by default there and it tends to look best with many arcade games, and is also what a majority of folks using CRT will see unless they have special models with image adjustments for H/V sizing, or high-cost external tools like Extron devices.
