### ISSUE TITLE
Double dragon II aspect ratio option is possible?

### ISSUE THREAD

**Issue by suww37** [jotego/jtdd#23]
Hi~
Is possible "aspect ratio option" in double dragon 2 core? I want this option.
I know this option(apsect ratio) is possible in double dragon 1. Thank you~

**Comment by jotego** [comment]
Hello, 

I have fixed this in commit 38fecce. The files are available in the usual location.

**Comment by suww37** [comment]
> Hello,
> 
> I have fixed this in commit [56b8bfe](https://github.com/jotego/jtdd/commit/56b8bfe59d715525a33579b32dad406cf158237d). The files are available in the usual location.

Sorry for aspect ratio issue.  My mistake. I cant hear your fixed dd2 effect sound.

**Comment by jotego** [comment]
Thank you for raising that issue. I had not noticed it. It came from an error introduced while fixing the PCM in the "Midnight Resistance" core.
I have fixed it in 0cf900f. It now works correctly for both DD2 and Midnight Resistance.
