### ISSUE TITLE
[kunio] schematics changes

### ISSUE THREAD

**Issue by jotego** [jotego/jtdd#29]
Please make the following changes:

- [x] rename MAIN_SUM bus to YDIFF, because it takes the difference of the vertical screen position and the object y coordinate
- [x] move OR gate CC7D closer to where the YDIFF is generated
- [x] MAIN_SUMA1 is not connected at the top level, remove the ports
- [x] rename MAIN_SUMA1 to YAUX
- [x] rearrange the sheet 8/16 so there are no devices close to the sheet edges

**Comment by etriana85** [comment]
The issue  are solved.
[Renegade(Kunio).pdf](https://github.com/jotego/jtdd/files/10123776/Renegade.Kunio.pdf)

**Comment by jotego** [comment]
The changes were done in jtsch. Please redo them in jtdd.

**Comment by etriana85** [comment]
This is solved again.
[kunio.pdf](https://github.com/jotego/jtdd/files/10133869/kunio.pdf)
