### ISSUE TITLE
Double Dragon crash on last stage

### ISSUE THREAD

**Issue by notsonic** [jotego/jtdd#31]
I was playing though Double Dragon in 2 player mode with a friend. The game crashed on the last level after the door opens. I did have turbo enabled.

![PXL_20230104_011437309](https://user-images.githubusercontent.com/3451329/210490589-c39d00de-ec9e-4c77-aace-360f7055b04b.jpg)

**Comment by jotego** [comment]
This is normal. The original game seems to have a bug and this can happen to you with the original PCB too. It may not happen on all game versions.
